In [14]:
import numpy as np
import random
import time
import matplotlib
import pandas as pd
import sys
import plotting
import numpy as np

In [15]:
class environment:
    def __init__(self):
        self.env_rows = 4
        self.env_columns = 4
        self.actions = ['up', 'right', 'down', 'left']
        self.V = np.zeros((self.env_rows, self.env_columns))
        self.P = np.array([[[0,0.5,0.5,0],  ## transition probability
                          [0,0.33,0.33,0.33],
                          [0,0,0,0],
                          [0,0,0.5,0.5]],
                          [[0.333,0.333,0.333,0],
                           [0,0,0,0],
                           [0.25,0.25,0.25,0.25],
                           [0,0,0,0]],
                           [[0.333,0.333,0.333,0],
                           [0.25,0.25,0.25,0.25],
                           [0.25,0.25,0.25,0.25],
                           [0.333,0,0.333,0.333]],
                           [[0,0,0,0],
                           [0.333,0.333,0,0.333],
                           [0,0,0,0],
                           [0.333,0,0.333,0.333]]]
                           )  ## probability transition
        self.policy = np.zeros((self.env_rows, self.env_columns))
        for i in range(self.env_rows):
            for j in range(self.env_columns):
                self.policy[i][j] = np.argmax(self.P[i,j])
        self.rewards = np.full((self.env_rows, self.env_columns), -1)
        self.rewards[0,2] = 100
        self.fire = {}
        self.fire[0] = []
        self.fire[1] = [1,3]
        self.fire[2] = []
        self.fire[3] = [0,2]
        for row_index in range(self.env_rows):
            for column_index in self.fire[row_index]:
                self.rewards[row_index, column_index] = -100
                

In [16]:
def parameters():
    
    epsilon = 0.9 #the percentage of time when we should take the best action (instead of a random action)
    discount_factor = 0.2 #discount factor for future rewards (gamma)
    learning_rate = 0.8 #the rate at which the agent should learn
    num_episodes = 1000
    episode_lengths = np.zeros(num_episodes)
    episode_rewards = np.zeros(num_episodes)
    return epsilon, discount_factor, learning_rate, num_episodes, episode_lengths, episode_rewards


In [17]:
env = environment()

In [18]:
V = env.V
policy = env.policy
probability = env.P
rewards = env.rewards

In [19]:
epsilon, discount_factor, learning_rate, num_episodes, episode_lengths, episode_rewards = parameters()

In [20]:
def get_next_location(current_row_index, current_column_index, action_index):
    new_row_index = current_row_index
    new_column_index = current_column_index
    if env.actions[action_index] == 'up' and current_row_index  > 0:
        new_row_index -= 1
    elif env.actions[action_index] == 'right' and current_column_index < env.env_columns - 1:
        new_column_index += 1
    elif env.actions[action_index] == 'down' and current_row_index < env.env_rows - 1:
        new_row_index += 1
    elif env.actions[action_index] == 'left' and current_column_index > 0:
        new_column_index -= 1
    return new_row_index, new_column_index

In [21]:
def policy_evaluation(theta=1e-9):

    while True: 
        delta = 0
        for i in range(len(V)):
            for j in range(len(V[i])):
                v = V[i][j]
                temp = 0
                for action, action_probability in enumerate(probability[i][j]):
                    new_row_index, new_column_index = get_next_location(i, j, action)
                    temp += (probability[i,j,action]*(rewards[new_row_index][new_column_index] + discount_factor*V[new_row_index][new_column_index]))
                V[i,j] = temp

                delta = max(delta, np.abs(V[i,j] - v))
                # Terminate if value change is insignificant
        if delta < theta:
            return V

In [22]:
def policy_improvement():
    policy_stable = np.full((env.env_rows, env.env_columns),True)
    for i in range(len(V)):
        for j in range(len(V[i])):
            action_value_array = np.array([])
            old_action = policy[i,j]
            for action, action_probability in enumerate(probability[i][j]):
                print(action, action_probability)
                new_row_index, new_column_index = get_next_location(i, j, action)
                action_value = rewards[new_row_index][new_column_index] + discount_factor * V[new_row_index][new_column_index]
                action_value_array = np.append(action_value_array, action_value)
            optimal_action = np.argmax(action_value_array)
            policy[i][j] = optimal_action
            if old_action != optimal_action:
                policy_stable[i][j] = False
    return policy_stable, policy  

In [23]:
for itr in range(100):
    V = policy_evaluation(theta=1e-9)
    policy_stable, policy = policy_improvement()
    count = 0 # count for what number of policies are false
    for i in range(env.env_rows):
        for j in range(env.env_columns):
            if policy_stable[i][j] == False:
                count +=1
                break
        if count >= 1:
            break
    if count == env.env_rows * env.env_columns:
        break

[[ -4.74962999  -0.64347558   0.           0.        ]
 [-36.85282431   0.         -26.78266278   0.        ]
 [-38.5960803  -32.66790091 -30.65325561 -38.61454855]
 [  0.         -69.1086822    0.         -39.14477066]]
0 0.0
1 0.5
2 0.5
3 0.0
0 0.0
1 0.33
2 0.33
3 0.33
0 0.0
1 0.0
2 0.0
3 0.0
0 0.0
1 0.0
2 0.5
3 0.5
0 0.333
1 0.333
2 0.333
3 0.0
0 0.0
1 0.0
2 0.0
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.333
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.25
1 0.25
2 0.25
3 0.25
0 0.333
1 0.0
2 0.333
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.0
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.0
2 0.333
3 0.333
[[ -4.74962999  -0.64347558   0.           0.        ]
 [-36.85282431   0.         -26.78266278   0.        ]
 [-38.5960803  -32.66790091 -30.65325561 -38.61454855]
 [  0.         -69.1086822    0.         -39.14477066]]
0 0.0
1 0.5
2 0.5
3 0.0
0 0.0
1 0.33
2 0.33
3 0.33
0 0.0
1 0.0
2 0.0
3 0.0
0 0.0
1 0.0
2 0.5
3 0.5
0 0.333
1 0.333
2 0.333
3 0.0


1 0.0
2 0.0
3 0.0
0 0.0
1 0.0
2 0.5
3 0.5
0 0.333
1 0.333
2 0.333
3 0.0
0 0.0
1 0.0
2 0.0
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.333
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.25
1 0.25
2 0.25
3 0.25
0 0.333
1 0.0
2 0.333
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.0
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.0
2 0.333
3 0.333
[[ -4.74962999  -0.64347558   0.           0.        ]
 [-36.85282431   0.         -26.78266278   0.        ]
 [-38.5960803  -32.66790091 -30.65325561 -38.61454855]
 [  0.         -69.1086822    0.         -39.14477066]]
0 0.0
1 0.5
2 0.5
3 0.0
0 0.0
1 0.33
2 0.33
3 0.33
0 0.0
1 0.0
2 0.0
3 0.0
0 0.0
1 0.0
2 0.5
3 0.5
0 0.333
1 0.333
2 0.333
3 0.0
0 0.0
1 0.0
2 0.0
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.333
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.25
1 0.25
2 0.25
3 0.25
0 0.333
1 0.0
2 0.333
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.0
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333


1 0.25
2 0.25
3 0.25
0 0.333
1 0.0
2 0.333
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.0
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.0
2 0.333
3 0.333
[[ -4.74962999  -0.64347558   0.           0.        ]
 [-36.85282431   0.         -26.78266278   0.        ]
 [-38.5960803  -32.66790091 -30.65325561 -38.61454855]
 [  0.         -69.1086822    0.         -39.14477066]]
0 0.0
1 0.5
2 0.5
3 0.0
0 0.0
1 0.33
2 0.33
3 0.33
0 0.0
1 0.0
2 0.0
3 0.0
0 0.0
1 0.0
2 0.5
3 0.5
0 0.333
1 0.333
2 0.333
3 0.0
0 0.0
1 0.0
2 0.0
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.333
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.25
1 0.25
2 0.25
3 0.25
0 0.333
1 0.0
2 0.333
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.0
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.0
2 0.333
3 0.333
[[ -4.74962999  -0.64347558   0.           0.        ]
 [-36.85282431   0.         -26.78266278   0.        ]
 [-38.5960803  -32.66790091 -30.65325561 -38.61454855]
 [  0.         -69.1086822

1 0.5
2 0.5
3 0.0
0 0.0
1 0.33
2 0.33
3 0.33
0 0.0
1 0.0
2 0.0
3 0.0
0 0.0
1 0.0
2 0.5
3 0.5
0 0.333
1 0.333
2 0.333
3 0.0
0 0.0
1 0.0
2 0.0
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.333
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.25
1 0.25
2 0.25
3 0.25
0 0.333
1 0.0
2 0.333
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.0
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.0
2 0.333
3 0.333
[[ -4.74962999  -0.64347558   0.           0.        ]
 [-36.85282431   0.         -26.78266278   0.        ]
 [-38.5960803  -32.66790091 -30.65325561 -38.61454855]
 [  0.         -69.1086822    0.         -39.14477066]]
0 0.0
1 0.5
2 0.5
3 0.0
0 0.0
1 0.33
2 0.33
3 0.33
0 0.0
1 0.0
2 0.0
3 0.0
0 0.0
1 0.0
2 0.5
3 0.5
0 0.333
1 0.333
2 0.333
3 0.0
0 0.0
1 0.0
2 0.0
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.333
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.25
1 0.25
2 0.25
3 0.25
0 0.333
1 0.0
2 0.333
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0

1 0.25
2 0.25
3 0.25
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.333
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.25
1 0.25
2 0.25
3 0.25
0 0.333
1 0.0
2 0.333
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.0
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.0
2 0.333
3 0.333
[[ -4.74962999  -0.64347558   0.           0.        ]
 [-36.85282431   0.         -26.78266278   0.        ]
 [-38.5960803  -32.66790091 -30.65325561 -38.61454855]
 [  0.         -69.1086822    0.         -39.14477066]]
0 0.0
1 0.5
2 0.5
3 0.0
0 0.0
1 0.33
2 0.33
3 0.33
0 0.0
1 0.0
2 0.0
3 0.0
0 0.0
1 0.0
2 0.5
3 0.5
0 0.333
1 0.333
2 0.333
3 0.0
0 0.0
1 0.0
2 0.0
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.333
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.25
1 0.25
2 0.25
3 0.25
0 0.333
1 0.0
2 0.333
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.0
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.0
2 0.333
3 0.333
[[ -4.74962999  -0.64347558   0.           0.        ]
 [-36.85282431   0.       

2 0.0
3 0.0
0 0.333
1 0.0
2 0.333
3 0.333
[[ -4.74962999  -0.64347558   0.           0.        ]
 [-36.85282431   0.         -26.78266278   0.        ]
 [-38.5960803  -32.66790091 -30.65325561 -38.61454855]
 [  0.         -69.1086822    0.         -39.14477066]]
0 0.0
1 0.5
2 0.5
3 0.0
0 0.0
1 0.33
2 0.33
3 0.33
0 0.0
1 0.0
2 0.0
3 0.0
0 0.0
1 0.0
2 0.5
3 0.5
0 0.333
1 0.333
2 0.333
3 0.0
0 0.0
1 0.0
2 0.0
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.333
3 0.0
0 0.25
1 0.25
2 0.25
3 0.25
0 0.25
1 0.25
2 0.25
3 0.25
0 0.333
1 0.0
2 0.333
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.333
2 0.0
3 0.333
0 0.0
1 0.0
2 0.0
3 0.0
0 0.333
1 0.0
2 0.333
3 0.333
[[ -4.74962999  -0.64347558   0.           0.        ]
 [-36.85282431   0.         -26.78266278   0.        ]
 [-38.5960803  -32.66790091 -30.65325561 -38.61454855]
 [  0.         -69.1086822    0.         -39.14477066]]
0 0.0
1 0.5
2 0.5
3 0.0
0 0.0
1 0.33
2 0.33
3 0.33
0 0.0
1 0.0
2 0.0
3 0.0
0 0.0
1 0.0


In [26]:
print(policy)

[[1. 1. 0. 3.]
 [0. 0. 0. 0.]
 [1. 1. 0. 3.]
 [0. 0. 0. 0.]]
